[tool.black]
line-length = 88
target-version = ['py38', 'py39', 'py310']
skip-string-normalization = false
extend-exclude = '''
/(
    migrations
|   static
|   templates
|   venv
|   \.venv
|   env
)/
'''